---
- name: Run Django collectstatic
  shell: "cd {{django_dir}}; {{ venv_python }} manage.py collectstatic"
  when: create_new_project == True

- name: fix Django directory permissions
  file:
    state: directory
    owner: "{{ remote_web_user }}"
    group: "{{ remote_web_group }}"
    recurse: yes
    path: "{{ django_dir }}"
  become: true