---

- name: delete a virtualenv if it exists
  shell: rm -rf {{ venv_path }}
  ignore_errors: yes
  become: true

- name: install python requirements
  pip:
    requirements=/vagrant/resources/python_requirements.txt
    state=latest
  become: true