# Generated by Django 2.2.5 on 2019-09-03 20:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=2)),
                ('division', models.CharField(max_length=2)),
                ('statefp', models.CharField(max_length=2, unique=True)),
                ('statens', models.CharField(max_length=8)),
                ('geoid', models.CharField(max_length=2)),
                ('stusps', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('lsad', models.CharField(max_length=2)),
                ('mtfcc', models.CharField(max_length=5)),
                ('funcstat', models.CharField(max_length=1)),
                ('aland', models.BigIntegerField()),
                ('awater', models.BigIntegerField()),
                ('intptlat', models.CharField(max_length=11)),
                ('intptlon', models.CharField(max_length=12)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='CongressionalDistricts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd116fp', models.CharField(max_length=2)),
                ('geoid', models.CharField(max_length=4)),
                ('namelsad', models.CharField(max_length=41)),
                ('lsad', models.CharField(max_length=2)),
                ('cdsessn', models.CharField(max_length=3)),
                ('mtfcc', models.CharField(max_length=5)),
                ('funcstat', models.CharField(max_length=1)),
                ('aland', models.BigIntegerField()),
                ('awater', models.BigIntegerField()),
                ('intptlat', models.CharField(max_length=11)),
                ('intptlon', models.CharField(max_length=12)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('statefp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='boundaries.States', to_field='statefp')),
            ],
        ),
    ]
