# Get Java ready for Hadoop

- name: Install add-apt-repostory
  become: yes
  apt: name=software-properties-common state=latest

- name: Add Oracle Java Repository
  become: yes
  apt_repository:
    repo: 'ppa:linuxuprising/java'

- name: Accept Java 11 License
  become: yes
  debconf:
    name: 'oracle-java11-installer'
    question: 'shared/accepted-oracle-license-v1-1'
    value: 'true'
    vtype: 'select'

- name: Install Oracle Java 11
  become: true
  apt:
    name: ['oracle-java11-installer', 'ca-certificates']
    state: latest

- name: correct java version selected
  alternatives:
    name: java
    path: "{{java_version_for_alternatives}}"

- name: correct java compiler version selected
  alternatives:
    name: javac
    path: "{{javac_version_for_alternatives}}"

- name: set JAVA_HOME variable
  lineinfile:
    path: /etc/environment
    insertafter: EOF
    line: 'JAVA_HOME="{{java_home}}"'