---

# basic system tasks

- name: set locale to {{locale}}
  action: command /usr/sbin/update-locale LANG={{locale}} LC_ALL={{locale}}
  become: true

- name: get tomcat packages for geoserver
  apt: name={{item}} state=latest install_recommends=yes update_cache=yes
  become: true
  with_items:
    - build-essential
    - unzip
    - tomcat7
    - tomcat7-admin
    - tomcat7-docs 
    - tomcat7-admin 
    - tomcat7-examples
    - git
    - ant
    - default-jdk

# just tomcat things

- name: create tomcat_users.xml from template
  template: src=tomcat_users.xml.j2 dest=/etc/tomcat7/tomcat-users.xml owner=root group=root mode=0644
  become: true

- name: restart tomcat
  service: name=tomcat7 state=restarted
  become: true

# download the geoserver .war file

- name: get the geoserver .war
  get_url: url=http://sourceforge.net/projects/geoserver/files/GeoServer/2.13.1/geoserver-2.13.1-war.zip dest=/vagrant/resources/geoserver.war.zip force=no
  become: true
  ignore_errors: yes
  register: geoserverwarexists
  when: geoserverwarexists is not defined

- name: unzip the geoserver .war file into its destination directory
  unarchive: src=/vagrant/resources/geoserver.war.zip dest=/var/lib/tomcat7/webapps copy=no
  become: true

- name: restart tomcat
  service: name=tomcat7 state=restarted
  become: true