---

# basic system tasks

- name: set locale to {{locale}}
  action: command /usr/sbin/update-locale LANG={{locale}} LC_ALL={{locale}}
  become: true

- name: get tomcat packages for geoserver
  apt:
    name: ['build-essential','unzip', 'tomcat9', 'tomcat9-admin', 'tomcat9-docs', 'tomcat9-admin', 'tomcat9-examples', 'git', 'ant', 'default-jdk']
    state: latest
    install_recommends: yes
    update_cache: yes
  become: true

# just tomcat things

- name: create tomcat_users.xml from template
  template:
    src: tomcat_users.xml.j2
    dest: /etc/tomcat9/tomcat-users.xml
    owner: root
    group: root
    mode: 0644
  become: true

- name: restart tomcat
  service: name=tomcat9 state=restarted
  become: true

- name: get the geoserver .war
  get_url:
    url: http://sourceforge.net/projects/geoserver/files/GeoServer/2.15.0/geoserver-2.15.0-war.zip
    dest: /vagrant/resources/src/geoserver.war.zip
    force: no
    validate_certs: no
  ignore_errors: yes
  register: geoserverwarexists
  when: geoserverwarexists is not defined

- name: unzip the geoserver .war file into its destination directory
  unarchive:
    src: /vagrant/resources/src/geoserver.war.zip
    dest: /var/lib/tomcat9/webapps
    remote_src: yes
  become: true
  when: geoserverwarexists

- name: restart tomcat
  service: name=tomcat9 state=restarted
  become: true

