---

# basic system tasks

- name: set locale to {{locale}}
  action: command /usr/sbin/update-locale LANG={{locale}} LC_ALL={{locale}}
  become: true

- name: get hadoop packages for geoserver
  apt: name={{item}} state=latest install_recommends=yes update_cache=yes
  become: true
  with_items:
    - build-essential
    - unzip
    - git
    - default-jdk

- name: Make sure we have a 'wheel' group
  group:
    name=wheel
    state=present

- name: Make sure that we have a 'hadoop' group
  group:
    name=hadoop
    state=present

- name: Make sure that vagrant user belongs to correct groups
  user:
    name: vagrant
    groups: wheel,hadoop
    append: yes


# download the Hadoop 3.1.1 directory

- name: get the Hadoop 3.1.1 code
  get_url: url=http://mirror.olnevhost.net/pub/apache/hadoop/common/hadoop-{{hadoop_version}}/hadoop-{{hadoop_version}}.tar.gz dest=/vagrant/resources/hadoop.tar.gz force=no
  become: true
  ignore_errors: yes
  register: hadoopdownloadexists
  when: hadoopdownloadexists is not defined

#- name: unzip the geoserver .war file into its destination directory
#  unarchive: src=/vagrant/resources/geoserver.war.zip dest=/var/lib/tomcat7/webapps copy=no
#  become: true
