---
- name: set locale to {{locale}}
  command: /usr/sbin/update-locale LANG={{locale}} LC_ALL={{locale}}
  become: true

- name: ensure aptitude is present
  apt:
    pkg: aptitude
    state: present
    install_recommends: yes
    update-cache: yes
  become: true

- name: update pre-installed packages after installing aptitude
  become: true
  apt: upgrade=full update_cache=yes

- name: install apt-file
  apt:
    pkg: apt-file
    state: present
    install_recommends: yes
  become: true

- name: install required system packages.
  apt:
    pkg: "{{ packages }}"
    state: present
    install_recommends: yes
    update-cache: yes
  become: true
  vars:
    - packages:
      - apt-file
      - build-essential
      - default-jdk
      - python3-setuptools
      - python3-pip
      - python3-apt
      - python3-pycurl
      - python3-software-properties
      - python3-virtualenv
      - python3-dev
      - vim
      - libpq-dev
      - python3-psycopg2
      - git
      - gdal-bin
      - postgresql
      - postgresql-contrib
      - postgis
      - postgis-doc

- name: do upgrades to newly installed packages
  apt: upgrade=yes
  become: true

- name: fix /etc/environment file
  lineinfile:
    path: /etc/environment
    regexp: '^PATH'
    line: 'PATH="$HOME/bin:$HOME/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"'
  become: true

- name: remove a src directory if it exists
  file:
    path: /vagrant/resources/src
    state: absent
  become: true

- name: create a src directory for downloaded code
  file:
    path: /vagrant/resources/src
    state: directory
    owner: vagrant
    mode: 0775
  register: srcdirectoryexists
  ignore_errors: true
  when: srcdirectoryexists.changed
  become: true

- name: create a directory for hadoop expansion
  file:
    path: /vagrant/resources/src/hadoop
    state: directory
    owner: vagrant
    mode: 0775
  ignore_errors: true
  become: true

- name: create a directory for hive expansion
  file:
    path: /vagrant/resources/src/hive
    state: directory
    owner: vagrant
    mode: 0775
  ignore_errors: true
  become: true