---
- name: install python 2
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  become: true

- name: set locale to {{locale}}
  command: /usr/sbin/update-locale LANG={{locale}} LC_ALL={{locale}}
  become: true

- name: ensure aptitude is present
  apt: >
    pkg=aptitude
    state=present
    install_recommends=yes
    update-cache=yes
  become: true

- name: update pre-installed packages after installing aptitude
  become: true
  apt: upgrade=full update_cache=yes

- name: install apt-file
  apt: >
    pkg=apt-file
    state=present
    install_recommends=yes
  become: true

- name: install required system packages.
  apt:
    pkg: "{{ packages }}"
    state: present
    install_recommends: yes
    update-cache: yes
  become: true
  vars:
    - packages:
      - apt-file
      - build-essential
      - python-setuptools
      - python-pip
      - virtualenvwrapper
      - supervisor
      - python-apt
      - python-pycurl
      - python-software-properties
      - python-virtualenv
      - python-dev
      - vim
      - libpq-dev
      - supervisor
      - python-psycopg2
      - git
      - gdal-bin
      - postgresql
      - postgresql-contrib
      - postgis
      - postgis-doc

- name: do upgrades to newly installed packages
  apt: upgrade=yes
  become: true



